/// A daily reflection generated by the AI curator.
///
/// Reflections are thoughtful summaries that mirror back themes
/// and patterns from the user's journal entries.
class Reflection {
  /// The date this reflection is for
  final DateTime date;

  /// The reflection content (markdown)
  final String content;

  /// When the reflection was generated
  final DateTime? generatedAt;

  const Reflection({
    required this.date,
    required this.content,
    this.generatedAt,
  });

  /// Whether this reflection has content
  bool get hasContent => content.trim().isNotEmpty;

  /// Get a preview of the reflection (first paragraph or first N characters)
  String get preview {
    if (content.isEmpty) return '';

    // Find first paragraph break
    final paragraphEnd = content.indexOf('\n\n');
    if (paragraphEnd > 0 && paragraphEnd < 300) {
      return content.substring(0, paragraphEnd);
    }

    // Otherwise truncate at character limit
    if (content.length > 200) {
      return '${content.substring(0, 200)}...';
    }

    return content;
  }

  @override
  String toString() {
    final dateStr = '${date.year}-${date.month.toString().padLeft(2, '0')}-${date.day.toString().padLeft(2, '0')}';
    return 'Reflection($dateStr, ${content.length} chars)';
  }
}
